### ISSUE TITLE
Extension installation issue with Magento-CE-2.1.16 

### ISSUE THREAD

**Issue by diamondzacx** [DivanteLtd/magento2-pimcore-bridge#1]
I have tried to install "magento2-pimcore-bridge" using composer but composer package is not available @https://packagist.org/. When that will be available?

Second option, i tried to install it by downloading code and copying it to Magento-CE-2.1.16 setup and followed the provided instructions after executing "php bin/magento setup:upgrade" - its' throwing 

![console](https://user-images.githubusercontent.com/16942728/50330926-00631b00-0523-11e9-938a-76bb6bd72582.png)

How can i upgrade it, I have also checked without copying "Magento 2 module for Pimcore integration" and Magento upgrade went fine. 

Second time while i ran it again by installing "Pimcore integration" module it's started throwing following....

"a:4:{i:0;s:303:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Divante_PimcoreIntegration schema: current version - none, required version - 1.0.4.13
Divante_PimcoreIntegration data: current version - none, required version - 1.0.4.13";i:1;s:2381:"#0 /var/www/magetwo/vendor/magento/f$
#1 /var/www/magetwo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext($
#2 /var/www/magetwo/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\C$
#3 /var/www/magetwo/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlug$
#4 /var/www/magetwo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext$
#5 /var/www/magetwo/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontContr$
#6 /var/www/magetwo/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlu$
#7 /var/www/magetwo/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\In$
#8 /var/www/magetwo/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Mag$
#9 /var/www/magetwo/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#10 /var/www/magetwo/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#11 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}

And when i am running "bin/magento setup:upgrade" - it's throwing the same error again and again. I stuck with blocker kind of situation.

**Comment by bartoszherba** [comment]
Hello @diamondzacx 
I made a mistake in README.md with versions compatibility. Module was tested with Magento 2.2.* not 2.1.*

In Magento 2.1.* there is no such an interface as CollectionProcessorInterface and therefore it is not possible to run this module. I will update compatibility page shortly.

Secondly, as for the second problem - it is the consequence that module was not installed properly and its version is still the same as prior to installation action. 

Sorry for the wrong version in readme.

**Comment by bartoszherba** [comment]
Closed due to inactivity.
