### ISSUE TITLE
Magento 2.2 end of life. now what?

### ISSUE THREAD

**Issue by operator888** [DivanteLtd/magento2-pimcore-bridge#11]
Hello, 
According to https://magento.com/sites/default/files/magento-software-lifecycle-policy.pdf  
Magento 2.2 reached the end of its life the last month. 
On the https://go.divante.xom/magento-pimcore-connector/  they say that Supported versions
are only  Magento 2.2.x and Pimcore 5.2 and above.

When is expected to support the 2.3.x Magento versions? 
I cant find any roadmap or related information, can someone clarify this to me?

Thank you

**Comment by bartoszherba** [comment]
Hello,
We are currently supporting Magento 2.3.x.
With regards to the future developments or roadmap, at the moment we have further plans for that but I recommend to observe this repo to get a fresh news about future work.

**Comment by operator888** [comment]
@bartoszherba ok! 
Thanks for the reply. I'll stay tuned.
