### ISSUE TITLE
Support for Magento 2.3.x

### ISSUE THREAD

**Issue by wujku** [DivanteLtd/magento2-pimcore-bridge#8]

**Comment by bartoszherba** [comment]
@wujku 
We are supporting M2 2.3.x, is there any reason that you have raised up empty issue without any details?

**Comment by gdvisser** [comment]
Hello,

I think this question is because of compatibility section in readme, refer to: https://github.com/DivanteLtd/magento2-pimcore-bridge#user-content-compatibility

It says `This module is compatible with Magento 2.2.x`.
But this information is outdated and Magento 2.3.x is supported also?

**Comment by bartoszherba** [comment]
Hello,
I have just update README so its current now. We are supporting M2 2.3.x

**Comment by gdvisser** [comment]
Thx!
